services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:4815df572d135ce24c14ec3c150e482c98693bc5cc20291693b582baab8eb0bf
    command: agent
    restart: unless-stopped
    ports:
      - "7007:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:00829897142460910ed1de162b166d2494916c061ecdb092de3b0653818c02b9
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.optimistic.cloud
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

volumes:
  beszel-socket:
    name: beszel-socket
  beszel-agent-data:
    name: beszel-agent-data