services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest@sha256:ff4d7287a4f75f2dca2265313cad6b97ea82547d931ee6198a8814de9dff52b1
    command: agent
    restart: unless-stopped
    ports:
      - "7007:7007"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  beszel-agent:
    image: henrygd/beszel-agent:latest@sha256:67b51e7976da13b7ce15e0270869827d54aa3df8cf0978e240e4105f62395a46
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel-agent-data:/var/lib/beszel-agent
      - beszel-socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.optimistic.cloud
      TOKEN: ${BESZEL_TOKEN}
      KEY: ${BESZEL_KEY}

volumes:
  beszel-socket:
    name: beszel-socket
  beszel-agent-data:
    name: beszel-agent-data